### ISSUE TITLE
NPC Note Moving to Top on Change

### ISSUE THREAD

**Issue by tmilktoast** [carlonicora/obsidian-rpg-manager#130]
I've been trying to save this report until I could figure out the circumstances of when and why it's happening. But no luck so far. 

On some of my NPCs, when I make any edits the note will jump back up to the top of the NonPlayerCharacter table. 

I don't believe it's a case of funky frontmatter. If I remove all of the links in a document it will stop doing it. Nothing shows up in the console when this happens. 

I tried remaking the same NPC from scratch using Create New NonPlayerCharacter, rather than using the Fill method which is how I made them originally, but the same issue persists. 

Here's frontmatter from one of them:

```
---
alias: [Cleopatra]
tags:
  - rpgm/npc/1
completed: false
synopsis: "an edgerunner and tech involved in the [[Dreamchip]] theft job. She installed the Cleopatra chip and has now taken over [[Jewel of the Nile Enterprises|JNE]], formerly HSE."
image: ""
goals: ""
pronoun: "s"
dates:
  dob: 12/23/2046
  death: 
---
```
