### ISSUE TITLE
Unlinked Relationships

### ISSUE THREAD

**Issue by thegiftofgabes** [carlonicora/obsidian-rpg-manager#14]
It would be great to show unlinked relationships. For example:

```
alias: []
tags: [rpgm/element/character/npc/1]
synopsis: "A resourceful teenager who runs errands for Ibis."
goals: "To become a FastDev. And to punch that asshole Becky in the face."
pronoun: she/her
dates:
 dob: 
 death: 
relationships: 
 characters: 
  Ibis: "A kind of older sister to Telma. Not that Telma will ever admit it."
  Parents: "Mother is AWOL."
 factions: 
 locations: 
completed: false
```

In the case above, Ibis is a character with their own page. But "parents" definitely are not, being a kind of "relationship" note that I find relevant in this character's presentation. Ibis appears in the display block, with a link to her page, but "Parents" won't appear at all unless I create a page for that, which is unnecessary.

I believe that allowing un-linked relationships to appear is useful both to add extra bits of info in a handy, intuitive location, and it's a cue for relationships you intend to create notes for later.
