### ISSUE TITLE
Add start/stop button for keeping track of the scenes times

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#76]
The scene has a start time and an end time in the frontmatter. Maybe it would be best to move it to a simpler `duration` to be tracked with a `start timer` and `end timer` that calculates the duration of a session regardless of the start time and end time.

**Comment by carlonicora** [comment]
### What if...

What if I add a new YAML key in the `SceneNavigation` code block looking like this:

```yaml
duration: hh:mm
durations:
  - [start, stop]
  - [start, stop]
```
