### ISSUE TITLE
Relationships definition

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#88]
Each relationship in the new `relationships` code block should implement a `RelationshipInterface` which is YAML-compatible.

```yaml
relationships:
  `ComponentType`:
    [[link]]:
      type: `RelationshipType`
      description: "relationship description"
```

This allows for future expansion of the relationships between elements.

The `RelationshipType` can specify the required boundaries:
- parent/child
- one way
- two ways (_default_)
