### ISSUE TITLE
Transform model-specific navigation code block to `component` codeblock

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#89]
The model-specific navigation code block (ie: `campaignNavigation`) should be renamed to `component`. The information on the type of component is already embedded in the rpgm tag, therefore the decision on which data to add to it is already in the component itself.

**Comment by carlonicora** [comment]
## Note to self

What's the difference between a `component` and a `navigation` code block? The reality is that they should be similar, and the only difference is in the data they contain.
The data, however, is held at a different stage, which is the model or sub-model stage.

One option is to move the definition of the content of the `component` in the codeblock itself:
```
models:
- header
- characterList
- nonplayercharacterlist
- ...
```

This would allow every user to specify the type of list they want to see directly in the code block. The challenge is to specify the type of relationships and the title (_which makes the code block more complicated_)...

```
models:
- header
- lists:
  - characters: "all | univocal | biunivocal | parent | child | reverse", "title"
relationships:
 - type: 1 <- RelationshipType, maybe using a text value instead of int-value!
   path: `path to relationship`
  description: ""
```
